project_name: kubeconform
builds:
  - main: ./cmd/kubeconform
    env:
      - CGO_ENABLED=0
      - GOFLAGS = -mod=vendor
      - GO111MODULE = on
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    flags:
      - -trimpath
      - -tags=netgo
      - -a
    ldflags:
      - -extldflags "-static"
      - -X main.version={{.Tag}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName  }}-{{ .Os  }}-{{ .Arch  }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

dockers:
  - image_templates:
      - 'ghcr.io/yannh/kubeconform:latest'
      - 'ghcr.io/yannh/kubeconform:{{ .Tag }}'
      - 'ghcr.io/yannh/kubeconform:{{ .Tag }}-amd64'
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64
  - image_templates:
      - 'ghcr.io/yannh/kubeconform:latest-alpine'
      - 'ghcr.io/yannh/kubeconform:{{ .Tag }}-alpine'
      - 'ghcr.io/yannh/kubeconform:{{ .Tag }}-amd64-alpine'
    dockerfile: Dockerfile-alpine
    build_flag_templates:
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64

checksum:
  name_template: 'CHECKSUMS'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'
